return {
  "MeanderingProgrammer/treesitter-modules.nvim",
  dependencies = { "nvim-treesitter/nvim-treesitter" },
  ---@module 'treesitter-modules'
  ---@type ts.mod.UserConfig
  opts = {
    ensure_installed = {
      "bash",
      "css",
      "gitcommit",
      "git_config",
      "gitignore",
      "ini",
      "json",
      "jsonc",
      "kdl",
      "kitty",
      "lua",
      "markdown",
      "markdown_inline",
      "passwd",
      "query",
      "regex",
      "ssh_config",
      "toml",
      "vim",
      "vimdoc",
      "yaml",
    },
    fold = { enable = true },
    highlight = { enable = true },
    incremental_selection = { enable = true },
    indent = { enable = true },
  },
}
